import type { Plan, SpecIR } from "@spc/schema";

export function renderPlan(plan: Plan, ir: SpecIR | null = null): string {
  const lines: string[] = [];
  lines.push(`Plan: ${plan.metadata.id}`);
  lines.push(`Spec: ${plan.spec.id}@${plan.spec.digest.slice(0, 19)}…`);
  lines.push(`Repo: ${plan.repository.revision.slice(0, 7)} (snapshot ${plan.repository.snapshotDigest.slice(7, 14)})`);
  if (plan.metadata.generatedBy) {
    lines.push(`Generated by: ${plan.metadata.generatedBy.provider}${plan.metadata.generatedBy.model ? ` (${plan.metadata.generatedBy.model})` : ""}`);
  }
  lines.push("");

  if (ir) {
    const covered = new Set(plan.tasks.flatMap((t) => [...(t.satisfies ?? []), ...(t.verifies ?? [])]));
    lines.push("Requirements covered:");
    for (const p of ir.properties) {
      lines.push(`  ${p.id} ${covered.has(p.id) ? "✓" : "✗"}`);
    }
    lines.push("");
  }

  lines.push("Execution:");
  const byId = new Map(plan.tasks.map((t) => [t.id, t]));
  const roots = plan.tasks.filter((t) => (t.dependsOn ?? []).length === 0 || (t.dependsOn ?? []).some((d) => !byId.has(d)));
  const order: string[] = [];
  const visit = (t: Plan["tasks"][number], depth: number, seen = new Set<string>()): void => {
    if (seen.has(t.id)) return;
    seen.add(t.id);
    order.push(`${"  ".repeat(depth)}${t.id} ${t.title} [${t.kind}]`);
    for (const child of plan.tasks.filter((c) => (c.dependsOn ?? []).includes(t.id))) {
      visit(child, depth + 1, seen);
    }
  };
  for (const r of roots.length > 0 ? roots : [plan.tasks[0]!]) visit(r, 0);
  for (const t of plan.tasks) {
    if (!order.some((l) => l.startsWith(t.id))) order.push(`${t.id} ${t.title} [${t.kind}]`);
  }
  lines.push("", ...order.map((o) => `  ${o}`), "");

  const writes = plan.tasks.flatMap((t) => (t.targets?.write ?? []).map((w) => `${t.id}: ${w}`));
  if (writes.length > 0) {
    lines.push("Expected writes:", "", ...writes.map((w) => `  ${w}`), "");
  }
  if (plan.assumptions?.length) {
    lines.push("Assumptions:", "", ...plan.assumptions.map((a) => `  - ${a}`), "");
  }
  if (plan.followups?.length) {
    lines.push("Follow-up drafts:", "");
    for (const f of plan.followups) {
      lines.push(`  ${f.blocking ? "[blocking] " : ""}${f.type}: ${f.title}`);
    }
    lines.push("");
  }
  return lines.join("\n");
}
