import { evidenceTrustLabel } from "@spc/schema";
import type { Evidence, FollowUp, RunState, SpecIR } from "@spc/schema";

/**
 * PR body generation (§82): a run can produce the pull-request title and
 * description - requirements addressed, verification evidence, known
 * limitations, follow-ups. Humans still decide whether to open or merge;
 * nothing is posted automatically.
 */

export interface PrInput {
  specIr: SpecIR;
  runState: RunState;
  followups: FollowUp[];
  evidence: Evidence[];
  diffStat?: string;
}

export interface PrDraft {
  title: string;
  body: string;
}

export function renderPrDraft(input: PrInput): PrDraft {
  const { specIr, runState } = input;
  const evidenceById = new Map(input.evidence.map((e) => [e.id, e]));
  const satisfied = specIr.properties.filter((p) => runState.requirements[p.id]?.status === "satisfied");
  const openFollowups = input.followups.filter((f) => f.status === "open");
  const weak = specIr.properties.filter((p) => runState.requirements[p.id]?.weakEvidence);

  const title = `spc: ${specIr.spec.metadata.title} (${satisfied.length}/${specIr.properties.length} properties satisfied)`;

  const lines: string[] = [];
  lines.push(`## What`, "");
  lines.push(`Applied plan \`${runState.planId ?? "-"}\` for spec **${specIr.spec.metadata.id}** (${specIr.spec.metadata.title}).`);
  lines.push(`Run: \`${runState.runId}\` · status: **${runState.status.replace("_", " ")}**`);
  if (runState.branch) lines.push(`Branch: \`${runState.branch}\``);
  lines.push("");

  lines.push(`## Requirements`, "");
  lines.push("| Property | Priority | Observed | Evidence |", "| --- | --- | --- | --- |");
  for (const p of specIr.properties) {
    const state = runState.requirements[p.id];
    const evs = (state?.evidenceIds ?? [])
      .map((id) => evidenceById.get(id))
      .filter((e): e is Evidence => e !== undefined)
      .map((e) => `${evidenceTrustLabel(e.kind)}:${e.outcome}`)
      .join(", ");
    lines.push(`| ${p.id} | ${p.priority} | ${state?.status ?? "unknown"} | ${evs || "-"} |`);
  }
  lines.push("");

  if (input.diffStat) {
    lines.push(`## Changes`, "", "```", input.diffStat, "```", "");
  }

  lines.push(`## Verification`, "");
  lines.push(
    `- ${input.evidence.filter((e) => e.kind === "test" || e.kind === "command").length} deterministic command/test evidence records`,
    `- ${input.evidence.filter((e) => e.kind === "agent").length} model-derived evidence records`,
    `- ${input.evidence.filter((e) => e.kind === "human").length} human evidence records`,
    "",
  );

  if (openFollowups.length > 0) {
    lines.push(`## Open follow-ups`, "");
    for (const f of openFollowups) lines.push(`- ${f.blocking ? "**[blocking]** " : ""}${f.id}: ${f.title}`);
    lines.push("");
  }

  if (weak.length > 0) {
    lines.push(`## Known limitations`, "");
    for (const p of weak) lines.push(`- ${p.id} is verified by non-deterministic evidence only.`);
    lines.push("");
  }

  lines.push(`---`, "", `_Generated by spc from run records; review the diff, not this summary._`);
  return { title, body: lines.join("\n") };
}
